### ISSUE TITLE
Plans WRT LoLA?

### ISSUE THREAD

**Issue by fenollp** [hlisdero/cargo-check-deadlock#16]
Hi! Very interesting project!

Any plans on rewriting `LoLA` to Rust? Surely, going further, this project would benefit from importing `LoLA` instead of spawning a process.
Sub-question: what's the state of `LoLA`'s development? Their paper was published 23 years ago and they seem to release tarballs on a webpage...

Do you feel that something else could replace `LoLA`? You seem to have organized your codebase thus.

**Comment by Skasselbard** [comment]
LoLa is developed at the University of Rostock by [Prof. Wolf](https://theo.informatik.uni-rostock.de/en/karsten-wolf/) and his graduate students (1-2) at the [chair in Theoretical Computer Science ](https://theo.informatik.uni-rostock.de/en/). I am pretty sure that LoLa will not be rewritten, as it is developed parallel to the academic duties. But, LoLa is still in development and updated with current research for the foreseeable future.

LoLa could be replaced by another Petri net model checker. There is a [model checking contest](https://mcc.lip6.fr/2023/index.php) where other tools can be found ([last results whit LoLa](https://mcc.lip6.fr/2021/results.php)). I believe [Tapaal](https://www.tapaal.net/) was always a main competitor of LoLa. However, I don't think there is a rust competitor, and it is unlikely that any of the existing projects will change the codebase, since these model checkers are highly optimized to squeeze out every bit of performance.
